services:
  web:
    build: .
    environment:
      - DEBUG_MODE=${DEBUG}
    depends_on:
      - redis
    # healthcheck:
    #   test: [ "CMD-SHELL", "curl -f http://localhost:5000/health" ]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 3
    # network_mode: "host"
    ports:
      - "127.0.0.1:5000:5000"
  redis:
    image: "redis:alpine"
